# Generated by Django 3.1.7 on 2021-07-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='hood',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='location',
            field=models.CharField(choices=[('Kisumu', 'Kisumu'), ('Mombasa', 'Mombasa'), ('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Kilifi', 'Kilifi')], default='Kisumu', max_length=100),
        ),
    ]
