# Generated by Django 3.1.7 on 2021-07-24 23:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood', '0005_business_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upcoming_events',
            new_name='UpcomingEvents',
        ),
    ]
