# Generated by Django 3.1.7 on 2021-07-25 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0007_auto_20210725_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='hood',
        ),
    ]
