# Generated by Django 3.1.7 on 2021-07-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0008_remove_neighborhood_hood'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='admin',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
