# Generated by Django 3.1.7 on 2021-07-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0010_auto_20210725_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='health_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='police_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
