# Generated by Django 3.1.7 on 2021-07-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0011_auto_20210725_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='user',
        ),
    ]
