# Generated by Django 3.1.7 on 2021-07-26 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0015_auto_20210726_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='hood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hood.neighborhood'),
            preserve_default=False,
        ),
    ]
