# Generated by Django 3.1.7 on 2021-07-27 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0016_auto_20210726_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
    ]
